### PR TITLE
Some fixes, altering and the config file extending.

### PR DESCRIPTION
**Pull request by sprnza**
Hi there!
Thank you for this brilliant idea! 
I'd like to propose some fixes and the config file extending.
So what I've done is:
1) Read ssl_verify_cert from .nextcloud_cal.ini (urllib3 was throwing warnings with False)
2) Added "urgent_words", "urgent_cals" and "urgent_color" in order to have some events or entire calendar to be highlighted with a desired color.
3) Fixed issue when only last event in reccurance was added to the results
4) Added lines_to_display and time_delta in the config file plus fixed counting number of lines to display.
5) Replaced /t with two spaces between timestr and SUMMARY

Lines 99-101 look ugly, but I haven't came up with another idea :)

### CODE REVIEW

**Comment by greenorca** [comment]
Hello,
thanks a lot lot for your commit! You actually fixed an really odd bug with frequently missing events. 
As well, many thanks for enhancing the config file and the colourization of the output. I don't see a way to streamline your above mentioned lines either. At least I'll add some more comments for general readability ;-)
Being very thankful - best regards!
Sven

**Comment by sprnza** [comment]
You're welcome! :) I'm about to add another pull request actually :)

**Comment by greenorca** [comment]
ahh, ohh, just pushed a few minor bits up in the master branch...

**Comment by greenorca** [comment]
Would you like to commit the "Today" change again? Would be nice :-)

**Comment by sprnza** [comment]
I've already done that. I just had been scared by a sign "Contains conflicts, couldn't be merged" but then found out that I'm not able to do anything with it. You'll need to merge manually :) See the pull requests

**Pull request merged**
